version: "3.0"
services:
  db:
    image : mysql:8
    container_name: nojpadb
    environment:
      MYSQL_ROOT_PASSWORD: tnsqja4856
      MYSQL_USER : hong
      MYSQL_PASSWORD : tnsqja4856
      MYSQL_DATABASE : todo
      ports: "3306:3306"
  application:
    build : .
    restart : on-failure
    ports :
      - "80:8080"
    depends_on:
      - db
    container_name: nojpa

    environment:
       -DATABASE_HOST : db
       -DATABASE_USER : hong
       -DATABASE_NAME : todo
       -DATABASE_PORT : 3306
#      SPRING_DATASOURCE_URl: jdbc:mysql://db:3306/todo?autoReconnect=true&useSSL=true&serverTimezone=Asia/Seoul
#      SPRING_DATASOURCE_USERNAME: hong
#      SPRING_DATASOURCE_PASSWORD: tnsqja4856

