version: "3.0"
services:
  database:
    image : mysql:8
    container_name: nojpadb
    environment:
      MYSQL_ROOT_PASSWORD: tnsqja4856
      MYSQL_USER : hong
      MYSQL_PASSWORD : tnsqja4856
      MYSQL_DATABASE : todo
      ports: "3306:3306"
  application:
    build : .
    restart : on-failure
    ports :
      - "80:8080"
    depends_on:
      - database
    container_name: nojpa

    environment:
      SPRING_DATASOURCE_URl: jdbc:mysql://nojpadb:3306/todo?autoReconnect=true&useSSL=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: hong
      SPRING_DATASOURCE_PASSWORD: tnsqja4856
